board/urls.py
from django.urls import path
from .views import ItemLV,content_comment,ItemCV,ItemDeleteView,itemLV,test1,test

app_name = 'spring'

urlpatterns = [
    path('',ItemLV.as_view(),name='index'),
    path('detail/<int:pk>',content_comment,name='detail'),
    path('create/',ItemCV.as_view(),name='create'),
    path('delete/<int:pk>',ItemDeleteView.as_view(),name='delete'),
    
    path('f/',itemLV),
    path('lion/<int:pk>/',test1),
    path('lion/tiger/',test),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("board.urls")),
]

board/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()

class Comment(models.Model):
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    comment = models.TextField

board/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields =['comment']

board/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,DeleteView
from .models import Item
from django.urls import reverse_lazy
from .forms import CommentForm
from django.http import HttpResponse

class ItemLV(ListView):
    model = Item    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['name'] = 'Tiger'
        return context    

class ItemDV(DetailView):
    model = Item    

class ItemCV(CreateView):
    model = Item
    success_url = reverse_lazy('spring:index')
    fields = ['title','content']

def content_comment(request,pk):
    item = Item.objects.get(pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.item = item
            comment.save()
        elif request.method == "GET":
            form = CommentForm()
        return render(request, 'board/item_detail.html',{'object':item,'form':form})
    
class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy('spring:index')

def itemLV(request):
    object = Item.objects.all()
    name = "Lion"
    context = {
        'object_list' : object,
        'name' : name
    }
    return render(request=request,template_name='board/item_list.html',context = context)

def test(request):
    return HttpResponse("요청 잘 받았어")

def test1(request,pk):
    return HttpResponse(f"tes1 pk : {pk} 이야")

board/templates/board/item_confirm_delete.html
<form method="post">{% crsf_token %}
    <p>정말로 삭제하시겠습니까?</p>
    <input type = "submit" value = "Yes, delete it">
</form>

board/templates/board/item_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="container">
    <div class="container my-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{object.title}} </h5>
                <p>{{object.content}}</p>
            </div>
        </div>
    </div> 
    <div>
        <form action="{% url 'spring:delete' object.id %}">
        <input type="submit" value="삭제" class="btn btn-primary">
        </form>
    </div>
    <div class="container">
        <h6 class="border-bottom pb-2">댓글 등록하기</h6>
        <div>
            <form action="" method="post">
                {% csrf_token%}
                {{form.as_p}}
                <input type="submit" value="저장하기" class="btn btn-primary">
            </form>
        </div>
        <div class="container">
            <div class="list-group">
                {% for c in object.comment_set.all %}
                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <!-- <h5 class="mb-1">댓글</h5> -->
                        <!-- 여기에 댓글 작성자나 작성 시간 등 추가 정보를 표시할 수 있습니다. -->
                    </div>
                    <p class="mb-1">{{ c.comment }}</p>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>    
</body>

board/templates/board/item_form.html
<form action = "" method="post">
    {% csrf_token%}
    {{form.as_p}}
    <button type = "submit">Submit</button>
</form> 

board/templates/board/item_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body class="container">    
    <h1>List View</h1>
    {% for object in object_list %}
    <div>
    <h3><a href="{% url 'spring:detail' object.id %}">{{object.title}}</a></h3>
    </div>
    {% endfor %}
    
    <div>
        <form action="{% url 'spring:create'%}">
        <input type="submit" value="글쓰기" id="">
        </form>
    </div>
</body>
</html>